name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v5
      with:
        go-version: 1.25
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v5

    - name: Build for macos
      if: runner.os == 'MacOS'
      run: |
        go build -v . || /bin/true
        zip -r gollercoaster-macos.zip textures.png gollercoaster music/*.mp3

    - name: Build for Linux
      if: runner.os == 'Linux'
      run: |
        git clone https://github.com/jrcichra/gh-actions-telegraf
        bash gh-actions-telegraf/telegraf.sh
        sudo apt-get install -y libgl1-mesa-dev xorg-dev libasound2-dev
        go build -v .
        zip gollercoaster-linux.zip textures.png gollercoaster music/*.mp3
      env:
        INFLUX_URL: ${{ secrets.INFLUX_URL }}
        INFLUX_USERNAME: ${{ secrets.INFLUX_USERNAME }}
        INFLUX_PASSWORD: ${{ secrets.INFLUX_PASSWORD }}
    - name: msys2 for Windows
      if: runner.os == 'Windows'
      uses: msys2/setup-msys2@v2

    - name: Build for Windows
      if: runner.os == 'Windows'
      run: |
        msys2 pacman -Syu --noconfirm
        msys2 pacman -S --noconfirm --needed zip base-devel mingw-w64-i686-toolchain mingw-w64-x86_64-toolchain git
        msys2 ls -l /c/hostedtoolcache/windows/go/1.14.1/x64/bin
        msys2 /c/hostedtoolcache/windows/go/1.14.1/x64/bin/go build
        msys2 ls -l
        msys2 zip gollercoaster-windows.zip textures.png gollercoaster.exe music/*.mp3
    - uses: actions/upload-artifact@v4
      with:
        name: gollercoaster
        path: "*.zip"
        
