name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest]
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build for Linux
      if: runner.os != 'Windows'
      run: |
        sudo apt-get install -y libgl1-mesa-dev xorg-dev
        go build -v .

    - name: msys2 for Windows
      if: runner.os == 'Windows'
      uses: numworks/setup-msys2@v1

    - name: Build for Windows
      if: runner.os == 'Windows'
      run: |
      msys2do pacman -S --noconfirm --needed base-devel mingw-w64-i686-toolchain mingw-w64-x86_64-toolchain
      msys2do echo 'export PATH=/mingw64/bin:$PATH' >> ~/.bashrc
      msys2do pacman -S --noconfirm git
      msys2do echo 'export PATH=/c/hostedtoolcache/windows/go/1.14.1/x64:$PATH' >> ~/.bashrc
      msys2do go build