name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build for macos
      if: runner.os == 'MacOS'
      run: |
        go build -v . || /bin/true
        zip -r gollercoaster-macos.zip castle.png gollercoaster

    - name: Build for Linux
      if: runner.os == 'Linux'
      run: |
        git clone https://github.com/jrcichra/gh-actions-telegraf
        bash gh-actions-telegraf/telegraf.sh
        sudo apt-get install -y libgl1-mesa-dev xorg-dev
        go build -v .
        zip gollercoaster-linux.zip castle.png gollercoaster
      env:
        INFLUX_URL: ${{ secrets.INFLUX_URL }}
        INFLUX_USERNAME: ${{ secrets.INFLUX_USERNAME }}
        INFLUX_PASSWORD: ${{ secrets.INFLUX_PASSWORD }}
    - name: msys2 for Windows
      if: runner.os == 'Windows'
      uses: numworks/setup-msys2@v1

    - name: Build for Windows
      if: runner.os == 'Windows'
      run: |
        msys2do pacman -Syu --noconfirm
        msys2do pacman -S --noconfirm --needed zip base-devel mingw-w64-i686-toolchain mingw-w64-x86_64-toolchain git
        msys2do ls -l /c/hostedtoolcache/windows/go/1.14.1/x64/bin
        msys2do /c/hostedtoolcache/windows/go/1.14.1/x64/bin/go build
        msys2do ls -l
        msys2do zip gollercoaster-windows.zip castle.png gollercoaster.exe
    - name: Release
      uses: ncipollo/release-action@v1.6.1
      with:
        tag: ${{ github.run_number }}
        artifacts: "*.zip"
        allowUpdates: "true"
        prerelease: "true"
        token: ${{ secrets.GITHUB_TOKEN }}
        